---
- hosts: localhost
  tasks:
    - name: Check if Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Install Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: "Install homebrew packages"
      homebrew:
        name: [
          'bash',
          'curl',
          'tmux',
          'unzip',
          'nvim',
          'zsh',
          'firefox',
          'librewolf',
          'kitty',
          'git',
          'docker',
          'docker-compose',
          'python3',
          'typescript',
          'rust',
          'golang',
          'pnpm'
        ]
        state: present
        update_homebrew: yes


    - name: "Ensure homebrew bash is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: /opt/homebrew/bin/bash 
      become: true

    - name: Set bash as the default shell
      shell: chsh -s /opt/homebrew/bin/bash
      become: true

